# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-vars

stages:
  - stage: Development
    displayName: Deploy to Development
    jobs:
      - deployment: DeployJob
        displayName: Deploy to Dev
        environment: development
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: PythonScript@0
                  inputs:
                    scriptSource: 'filePath'
                    scriptPath: './src/main.py'
                  env:
                    ADO_TOKEN: $(ADO_TOKEN)
                    ADO_ORG: $(ADO_ORG)


